
#ifndef CUPCAKE_ERROR_H
#define CUPCAKE_ERROR_H

#include "cupcake/Cupcake.h"

typedef uint32_t Error;

#define ERR_OK 0

// Generic errors
#define ERR_INVALID_ARGUMENT 1 // EINVAL, ENOPROTOOPT, WSAEINVAL,
// ERROR_INVALID_PARAMETER, ERROR_BAD_ARGUMENTS
#define ERR_INVALID_HANDLE 2 // ENOTSOCK, EBADF, WSAENOTSOCK
#define ERR_TOO_MANY_HANDLES 3 // ENFILE, EMFILE
#define ERR_ARGUMENT_OUT_OF_DOMAIN 4 // EDOM
#define ERR_BAD_ADDRESS 5 // EFAULT, WSAEFAULT
#define ERR_OUT_OF_MEMORY 6 // ENOMEM
#define ERR_NOT_SUPPORTED 7 // ENOTSUP, EOPNOTSUPP
#define ERR_ACCESS_DENIED 8 // EACCES, EPERM, EROFS, ERROR_ACCESS_DENIED,
                       // ERROR_CURRENT_DIRECTORY, ERROR_WRITE_PROTECT,
                       // ERROR_SHARING_VIOLATION
#define ERR_TIMED_OUT 9 // ETIMEDOUT, ETIME
#define ERR_NOT_INITIALIZED 10
#define ERR_INVALID_STATE 11
    
// Generic IO errors
#define ERR_BROKEN_PIPE 12 // EPIPE
#define ERR_IO_ERROR 13 // EIO
#define ERR_NO_LOCK_AVAILABLE 14 // ENOLCK
#define ERR_IO_CANCELED 15 // ECANCELED, WSA_OPERATION_ABORTED
    
// File IO errors
#define ERR_FILE_NOT_FOUND 16 // ENOENT, ERROR_FILE_NOT_FOUND, ERROR_INVALID_DRIVE
#define ERR_FILE_EXISTS 17 // EEXIST, ERROR_FILE_EXISTS, ERROR_ALREADY_EXISTS
#define ERR_FILE_IN_USE 18 // EBUSY, ETXTBSY
#define ERR_FILENAME_TOO_LONG 19 // ENAMETOOLONG, ERROR_BUFFER_OVERFLOW
#define ERR_IS_A_DIRECTORY 20 // EISDIR
#define ERR_NOT_A_DIRECTORY 21 // ENOTDIR
#define ERR_DIRECTORY_NOT_EMPTY 22 // ENOTEMPTY, ERROR_DIR_NOT_EMPTY
#define ERR_INVALID_SEEK 23 // ESPIPE
#define ERR_OUT_OF_SPACE 24 // ENOSPC, EDQUOT, ERROR_HANDLE_DISK_FULL, ERROR_DISK_FULL
#define ERR_NO_SUCH_DEVICE 25 // ENXIO, ENODEV
    
// File link errors
#define ERR_CROSS_DEVICE_LINK 26 // EXDEV
#define ERR_TOO_MANY_LINKS 27 // EMLINK, ELOOP
    
// Inet errors
#define ERR_NO_BUFFER_SPACE 400 // ENOBUFS, WSAENOBUFS
#define ERR_ADDRESS_NOT_SUPPORTED 401 // EAFNOSUPPORT
#define ERR_ADDRESS_IN_USE 402 // EADDRINUSE
#define ERR_ADDRESS_NOT_AVAILABLE 403 // EADDRNOTAVAIL
#define ERR_ALREADY_CONNECTED 404 // EISCONN
#define ERR_ARGUMENT_LIST_TOO_LONG 405 // E2BIG
#define ERR_CONNECTION_ABORTED 406 // ECONNABORTED, WSAECONNABORTED
#define ERR_CONNECTION_ALREADY_IN_PROGRESS 407 // EALREADY
#define ERR_CONNECTION_REFUSED 408 // ECONNREFUSED
#define ERR_CONNECTION_RESET 409 // ECONNRESET, WSAECONNRESET
#define ERR_CONNECTION_SHUTDOWN 410 // ESHUTDOWN, WSAESHUTDOWN
#define ERR_NOT_CONNECTED 411 // ENOTCONN, WSAENOTCONN
#define ERR_HOST_UNREACHABLE 412 // EHOSTUNREACH
#define ERR_NETWORK_DOWN 413 // ENETDOWN, WSAENETDOWN
#define ERR_NETWORK_RESET 414 // ENETRESET, WSAENETRESET
#define ERR_NETWORK_UNREACHABLE 415 // ENETUNREACH
#define ERR_DESTINATION_ADDRESS_REQUIRED 416 // EDESTADDRREQ
#define ERR_MESSAGE_TOO_LONG 417 // EMSGSIZE
#define ERR_PROTOCOL_ERROR 418 // EPROTO, EPROTONOSUPPORT
#define ERR_NOT_BOUND 419 // EDESTADDRREQ

// Address lookup errors
#define ERR_ADDR_FAMILY 500 // EAI_ADDRFAMILY
#define ERR_ADDR_NONAME 501 // EAI_NONAME
#define ERR_ADDR_NODATA 502 // EAI_NODATA
#define ERR_ADDR_FAIL 503 // EAI_FAIL

// Other errors
#define ERR_DEADLOCK 600 // EDEADLK
#define ERR_INVALID_TEXT 601 // EILSEQ

// Process errors
/*
#define ERR_NO_CHILD_PROCESS 10 // ECHILD
#define ERR_INVALID_EXECUTABLE 11 // ENOEXEC, ERROR_BAD_EXE_FORMAT
*/
    
    // Generic error for unmapped error code
#define ERR_UNKNOWN 1000

#endif // CUPCAKE_ERROR_H
