
#ifndef CUPCAKE_ASYNC_H
#define CUPCAKE_ASYNC_H

#include <functional>

namespace Cupcake {
    
namespace Async {

    /*
     * Runs the passed callback using the system thread pool, or one generated by the library.
     */
    void runAsync(std::function<void()> callback);
}

}

#endif // CUPCAKE_ASYNC_H
